apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: producao-hpa
  namespace: fast-order
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: producao-dep
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30