name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug - Listando arquivos na API
        run: ls -R src/Producao.Api
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: |
          cd src/Producao.Api
          dotnet restore Producao.Api.csproj

      - name: Build and publish
        run: |
          cd src/Producao.Api
          dotnet build Producao.Api.csproj -c Release --no-restore
          dotnet publish Producao.Api.csproj -c Release -o app/publish /p:UseAppHost=false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Ensure certs folder exists
        run: mkdir -p certs

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/producao-api:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/producao-api:${{ github.sha }} \
            .

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/producao-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/producao-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: | 
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install AWS CLI
        run: |
          sudo snap install aws-cli --classic

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name techchalenge-eks-cluster

      - name: Verify kubectl configuration
        run: |
          kubectl config view
          kubectl get nodes

      - name: Deploy to EKS Cluster
        run: |
          kubectl apply -f iac/kubernetes/namespace.yaml
          kubectl apply -f iac/kubernetes
          kubectl rollout status deployment/producao-dep -n fast-order
